title: Stu Sontier - cleanNFTs on HicetNunc
author: GitHub User
email: stu@stusontier.net
description: > # this means to ignore newlines until "twitter_username:"
  This github shows Stu Sontier's NFTs from       Hic et Nunc tezos-based cleanNFT project. Note that it is manually updated, not live.

# social links
twitter_username: StuSontier
github_username:  stumats
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: stusontierphoto
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# web related
website_url: "https://stusontier.net"

# Cryptocurrency Related
crypto_address_xtz: "tz1U8mFPuyGr48BWnULky9kUqAVQk8ewBHtU"
hicetnunc_profile_url: "https://www.hicetnunc.xyz/tz/tz1U8mFPuyGr48BWnULky9kUqAVQk8ewBHtU"

# Collections
collections:
  primary:
    output: true
    sort_by: list_priority


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in order as they should show up
#header_pages:
# - about.html


# Build settings
remote_theme: stumats/jeketnunc@main
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.md
